"""
Handler for /authorize command.
Allows users to authenticate via a code generated by the frontend.
"""
from time import monotonic

from telegram import Update
from telegram.ext import ContextTypes

from app.services.auth_code_service import auth_code_service
from app.core.security import create_access_token
from app.core.config import settings
from app.core.enums import RoleEnum
from app.core.authz import user_has_admin_role
from app.models.user import User


AUTHORIZE_ATTEMPT_LIMIT = 5
AUTHORIZE_ATTEMPT_WINDOW_SECONDS = 60


def _consume_authorize_attempt(user_data: dict, now: float | None = None) -> bool:
    current_time = monotonic() if now is None else now
    attempts = [
        timestamp
        for timestamp in user_data.get("authorize_attempts", [])
        if current_time - timestamp < AUTHORIZE_ATTEMPT_WINDOW_SECONDS
    ]
    if len(attempts) >= AUTHORIZE_ATTEMPT_LIMIT:
        user_data["authorize_attempts"] = attempts
        return False
    attempts.append(current_time)
    user_data["authorize_attempts"] = attempts
    return True


async def _reply_link_result(update: Update, error: str, full_name: str | None = None) -> None:
    if not error:
        await update.message.reply_text(
            "✅ Telegram berhasil dihubungkan.\n\n"
            f"Akun Booking Room {full_name or 'Anda'} sekarang dapat memakai Mini App dan perintah bot."
        )
        return

    messages = {
        "CODE_EXPIRED": "❌ Kode sudah kedaluwarsa atau pernah digunakan. Buat kode baru dari profil Booking Room.",
        "TELEGRAM_ALREADY_LINKED": "❌ Akun Telegram ini sudah terhubung ke user lain. Hubungi admin jika perlu dipindahkan.",
        "TARGET_ALREADY_LINKED": "❌ Akun Booking Room ini sudah terhubung ke Telegram lain. Putuskan koneksi lama terlebih dahulu.",
        "TARGET_USER_UNAVAILABLE": "❌ Akun Booking Room tujuan tidak aktif atau tidak tersedia. Hubungi admin.",
        "INVALID_TELEGRAM_USER": "❌ Identitas Telegram tidak valid. Buka ulang chat bot lalu coba lagi.",
    }
    await update.message.reply_text(messages.get(error, "❌ Kode koneksi tidak valid. Buat kode baru dari profil Booking Room."))


async def create_or_update_user(telegram_user_data: dict) -> User:
    """
    Create or update user from Telegram data.
    """
    from datetime import datetime
    from app.core.config import settings
    from app.models.user import User
    
    telegram_id = telegram_user_data["id"]
    
    # Check if user exists
    user = await User.find_one(User.telegram_id == telegram_id)
    
    # Build full name
    first_name = telegram_user_data.get("first_name", "")
    last_name = telegram_user_data.get("last_name", "")
    full_name = f"{first_name} {last_name}".strip()
    
    if user:
        # Update existing user
        user.full_name = full_name
        user.username = telegram_user_data.get("username")
        user.avatar_url = telegram_user_data.get("photo_url")
        user.last_login_at = datetime.now(settings.timezone)
        
        if telegram_id == settings.ADMIN_TELEGRAM_ID:
            user.role = RoleEnum.SUPER_ADMIN
        elif user.role is None:
            user.role = RoleEnum.STUDENT
        
        await user.save()
    else:
        # Create new user
        user = User(
            telegram_id=telegram_id,
            full_name=full_name,
            username=telegram_user_data.get("username"),
            avatar_url=telegram_user_data.get("photo_url"),
            role=RoleEnum.SUPER_ADMIN if telegram_id == settings.ADMIN_TELEGRAM_ID else RoleEnum.STUDENT,
            is_active=True,
            last_login_at=datetime.now(settings.timezone)
        )
        await user.insert()
    
    return user


async def authorize_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """
    Handle /authorize command.
    
    Usage: /authorize <code>
    
    User generates a code from the frontend, then sends it to the bot.
    The bot verifies the code and associates the user's Telegram identity with it.
    """
    # Check if code is provided
    if not context.args or len(context.args) != 1:
        await update.message.reply_text(
            "❌ Please provide a 6-digit code.\n\n"
            "Usage: /authorize <code>\n\n"
            "Example: /authorize 123456"
        )
        return
    
    code = context.args[0]
    
    # Validate code format (6 digits)
    if not code.isdigit() or len(code) != 6:
        await update.message.reply_text(
            "❌ Invalid code format.\n\n"
            "Code must be a 6-digit number.\n\n"
            "Example: /authorize 123456"
        )
        return
    
    # Get user info from Telegram
    user = update.effective_user
    
    if not user:
        await update.message.reply_text("❌ Could not identify user.")
        return

    if not _consume_authorize_attempt(context.user_data):
        await update.message.reply_text(
            "❌ Terlalu banyak percobaan. Tunggu satu menit sebelum mencoba lagi."
        )
        return
    
    print(f"🔍 Bot: /authorize command received from user {user.id}")
    print(f"🔍 Bot: Code to verify: {code}")
    
    # Verify code using auth_code_service directly
    code_data = await auth_code_service.verify_code(code)
    
    if not code_data:
        print(f"🔍 Bot: Code {code} is invalid or expired")
        await update.message.reply_text(
            "❌ Invalid or expired code.\n\n"
            "Please generate a new code from the frontend and try again."
        )
        return
    
    print(f"🔍 Bot: Code {code} is valid")
    
    # Prepare Telegram user data
    telegram_user_data = {
        "id": user.id,
        "first_name": user.first_name or "",
        "last_name": user.last_name or "",
        "username": user.username,
        "photo_url": None
    }

    if code_data.purpose == "telegram_link":
        success, error_msg, linked_user = await auth_code_service.complete_telegram_link(
            code,
            telegram_user_data,
        )
        await _reply_link_result(
            update,
            "" if success else error_msg,
            linked_user.full_name if linked_user else None,
        )
        return
    
    # Mark code as used with user data
    success, error_msg = await auth_code_service.mark_code_used(code, telegram_user_data)
    print(f"🔍 Bot: Mark code used result - success={success}, error={error_msg}")
    
    # Check for user mismatch
    if not success and error_msg == "USER_MISMATCH":
        await update.message.reply_text(
            "❌ Kode ini tidak valid untuk Anda.\n\n"
            "Kode otorisasi hanya dapat digunakan oleh akun Telegram yang membuatkannya.\n\n"
            "Silakan minta kode baru dari aplikasi."
        )
        print(f"🔍 Bot: User mismatch - code authorized for different user")
        return
    
    if not success:
        await update.message.reply_text(
            "❌ Gagal memproses kode otorisasi.\n\n"
            "Silakan coba lagi dengan kode baru."
        )
        print(f"🔍 Bot: Code marking failed - {error_msg}")
        return
    
    print(f"🔍 Bot: Code {code} marked as used")
    
    # Create or update user
    user_obj = await create_or_update_user(telegram_user_data)
    print(f"🔍 Bot: User created/updated: {user_obj.id}")
    
    # Generate JWT token
    access_token = create_access_token(data={"sub": str(user_obj.id)})
    print(f"🔍 Bot: Token generated successfully")
    
    # Build full name
    full_name = user_obj.full_name or "User"
    
    # Build success message (simplified, in Indonesian, without token)
    message = (
        f"✅ Otorisasi berhasil!\n\n"
        f"Selamat datang, {full_name}!\n\n"
        f"Anda akan otomatis login ke dashboard aplikasi.\n\n"
        f"🔗 Buka aplikasi: {settings.FRONTEND_URL}"
    )
    
    if user_has_admin_role(user_obj):
        message += "\n\n🔑 Anda memiliki hak akses admin."
    
    await update.message.reply_text(message)
    
    print(f"🔍 Bot: Authorization successful for user {user.id}")
